name: Package Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to package'
        required: true
        type: string

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - name: Prepare ZIP folder
        run: |
          mkdir output
          shopt -s extglob
          cp -r !(output) output/
          cp start.exe output/ || echo "No start.exe found"
          zip -r packaged-${{ github.event.inputs.branch_name }}.zip output

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: packaged-${{ github.event.inputs.branch_name }}
          name: Release for ${{ github.event.inputs.branch_name }}
          body: |
            Automatically packaged release for `${{ github.event.inputs.branch_name }}`
          files: packaged-${{ github.event.inputs.branch_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
